# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
  - lint
  - release
  - update_changelog

lint:
  stage: lint
  only:
    - develop
    - main
    - /(?:feature|bugfix|hotfix|release|support)\/[A-z,0-9,_,-]+/ # regex for gitflow
  script:
    - echo "linting code"
    - npm install
    - npm run lint

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  rules:
    - if: $CI_COMMIT_TAG # Run this job when a tag is created
  needs: ["lint"]
  script:
    - echo "running release_job"
  release: # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: $CI_COMMIT_TAG
    name: "Release $CI_COMMIT_TAG"
    description: "Castles & Crusades FoundryVTT Game System $CI_COMMIT_TAG Release"
    # assets:
    #   links:
    #     - name: "system.json"
    #       url: "https://gitlab.com/troll-lord/foundry-vtt/ruleset/castles-and-crusades/-/raw/$CI_COMMIT_TAG/system.json"

update-changelog:
  stage: update_changelog
  needs: ["release"]
  rules:
    - if: $CI_COMMIT_TAG # Run this job when a tag is created
  script: 
    - latestVersion=$(git describe --tags --abbrev=0)
    - currentVersion=$(grep -oP '(?<=VERSION ")([^"]*)' version.h)
    - |
      curl --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" --data "version=$currentVersion&from=$latestVersion&to=main&branch=main" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/repository/changelog"
  # only: 
  #   - release